[Android DeviceProfile]
CVars=r.MobileContentScaleFactor=0 ;0 = 原生分辨率渲染
CVars=r.SecondaryScreenPercentage.GameViewport=100 ; 副屏分辨率 ： 100 = 原生分辨率
CVars=slate.AbsoluteIndices=1  ; 启用 Slate UI 的绝对索引模式
CVars=r.Vulkan.RobustBufferAccess=1 ; 启用 Vulkan API 的 鲁棒缓冲区访问
CVars=r.Vulkan.DescriptorSetLayoutMode=2 ; 设置 Vulkan 的描述符集布局模式 ： 默认=2
CVars=r.Android.DisableVulkanSupport=1 ; 禁用 Vulkan 支持。设置为 1 则禁用 Vulkan。
CVars=r.Android.DisableVulkanSM5Support=1 ; 禁用 Vulkan 支持的 SM5（Shader Model 5）。
CVars=r.DefaultBackBufferPixelFormat=0 ; 设置默认的后备缓冲区像素格式。0表示标准格式。
CVars=r.MaxAnisotropy=4 ; 最大各向异性过滤级别
CVars=r.FrustumCullNumWordsPerTask=32 ; 设置用于视锥剔除的每个任务的词语数量，优化渲染性能。
CVars=r.SkyBlending.AllowSettingLerpPerFrame=0 ; 每帧设定天空融合的线性插值。
CVars=r.LandscapeLOD0ScreenSizeScale=1.5 ; LOD 远景缩放因子
CVars=r.Android.DisableVulkanSupport=0; 启用 Vulkan 支持
CVars=KuroLod.SetScreenSize=0 
CVars=r.imp.SSMbScaleLod0=1 ; 设置某些影像后处理的 LOD 缩放： 1 = 原生分辨率
CVars=r.imp.SSMbScaleLod1=1 ; 设置某些影像后处理的 LOD 缩放： 1 = 原生分辨率
TextureLODGroups=(Group=TEXTUREGROUP_HierarchicalLOD,MinLODSize=1,MaxLODSize=1024,LODBias=0,MinMagFilter=linear,MipFilter=point,MipGenSettings=TMGS_Unfiltered)
; 配置纹理的 LOD 组，定义了最小和最大纹理大小、过滤模式（线性过滤和点过滤），以及 MIP 生成设置。

[Android_VeryHigh DeviceProfile]
CVars=sg.ViewDistanceQuality=2 ; 视距质量
CVars=sg.AntiAliasingQuality=Cine ; 抗锯齿质量
CVars=sg.ShadowQuality=3 ; 阴影
CVars=sg.PostProcessQuality=2 ; 后期处理
CVars=sg.TextureQuality=2 ; 纹理
CVars=sg.EffectsQuality=2 ; 特效
CVars=sg.FoliageQuality=2 ; 植被
CVars=r.MobileContentScaleFactor=0.0 ; 设置原生分辨率渲染： 0.0 = 原生分辨率
CVars=r.SecondaryScreenPercentage.GameViewport=100 ; 副屏分辨率：100 = 原生分辨率
CVars=r.Mobile.WaterQuality=1 ; 水面质量
CVars=r.imp.SSMbScaleLod0=1 ; 影像后处理 LOD 缩放
CVars=r.imp.SSMbScaleLod1=1 ; 影像后处理 LOD 缩放 


; 以下是把你的手机强行以高配置运行
[Android_Default DeviceProfile]
BaseProfileName=Android_VeryHigh

[Android_Adreno4xx DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.UseLandscapeSrvBuffer=1
CVars=r.LandscapeForceMaterialLOD=1

[Android_Adreno5xx_Low DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Android.DisableFBFNonCoherent=1
CVars=r.UseLandscapeSrvBuffer=1
CVars=r.LandscapeForceMaterialLOD=1

[Android_Adreno5xx DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Android.DisableFBFNonCoherent=1
CVars=r.UseLandscapeSrvBuffer=1
CVars=r.LandscapeForceMaterialLOD=1

[Android_Adreno6xx_Low DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.UseLandscapeSrvBuffer=1
CVars=r.LandscapeForceMaterialLOD=1

[Android_Adreno6xx DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.UseLandscapeSrvBuffer=1
CVars=r.LandscapeForceMaterialLOD=1

[Android_Adreno6xx_High DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.UseLandscapeSrvBuffer=1
CVars=r.LandscapeForceMaterialLOD=1

[Android_Adreno7xx DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.UseLandscapeSrvBuffer=1

[Android_Adreno7xx_Low DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.UseLandscapeSrvBuffer=1

[Android_Adreno810 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.UseLandscapeSrvBuffer=1

[Android_Adreno8xx DeviceProfile]
BaseProfileName=Android_VeryHigh

[Android_Mali_G5x DeviceProfile]
BaseProfileName=Android_VeryHigh

[Android_Mali_G71 DeviceProfile]
BaseProfileName=Android_VeryHigh

[Android_Mali_G72 DeviceProfile]
BaseProfileName=Android_VeryHigh

[Android_Mali_G76 DeviceProfile]
BaseProfileName=Android_VeryHigh

[Android_Mali_G77 DeviceProfile]
BaseProfileName=Android_VeryHigh

[Android_Mali_G78 DeviceProfile]
BaseProfileName=Android_VeryHigh

[Android_Mali_G710 DeviceProfile]
BaseProfileName=Android_VeryHigh

[Android_Mali_G68 DeviceProfile]
BaseProfileName=Android_VeryHigh

[Android_Mali_G61x DeviceProfile]
BaseProfileName=Android_VeryHigh

[Android_Mali_G62x DeviceProfile]
BaseProfileName=Android_VeryHigh

[Android_Mali_G715 DeviceProfile]
BaseProfileName=Android_VeryHigh

[Android_Mali_G720 DeviceProfile]
BaseProfileName=Android_VeryHigh

[Android_Mali_G925 DeviceProfile]
BaseProfileName=Android_VeryHigh