[Core.System]
Paths=../../../Engine/Content
Paths=%GAMEDIR%Content
Paths=../../../Engine/Plugins/ThirdParty/ImpostorBaker/Content
Paths=../../../Engine/Plugins/json2struct/Content
Paths=../../../Engine/Plugins/Experimental/FieldSystemPlugin/Content
Paths=../../../Client/Plugins/LGUI/LGUI/Content
Paths=../../../Engine/Plugins/PrefabSystem/Content
Paths=../../../Engine/Plugins/FX/Niagara/Content
Paths=../../../Client/Plugins/Kuro/KuroGameplay/Content
Paths=../../../Client/Plugins/Puerts/Puerts/Content
Paths=../../../Client/Plugins/Wwise/Content
Paths=../../../Engine/Plugins/Editor/GeometryMode/Content
Paths=../../../Engine/Plugins/MovieScene/SequencerScripting/Content
Paths=../../../Engine/Plugins/Experimental/PythonScriptPlugin/Content
Paths=../../../Client/Plugins/CrashSight/Content
Paths=../../../Engine/Plugins/ThirdParty/QuickEditor/Content
Paths=../../../Client/Plugins/Kuro/TASdkPlugin/Content
Paths=../../../Engine/Plugins/rdLODtools/Content
Paths=../../../Client/Plugins/AudioMaterialPlugin/Content
Paths=../../../Engine/Plugins/Runtime/Nvidia/DLSS/Content
Paths=../../../Engine/Plugins/Runtime/Nvidia/Streamline/Content
Paths=../../../Engine/Plugins/Runtime/HoudiniEngine/Content
Paths=../../../Client/Plugins/Kuro/KuroHotPatch/Content
Paths=../../../Client/Plugins/Kuro/KuroImposter/Content
Paths=../../../Client/Plugins/Kuro/KuroAutomationTool/Content
Paths=../../../Engine/Plugins/FX/HoudiniNiagara/Content
Paths=../../../Client/Plugins/LogicDriverLite/Content
Paths=../../../Engine/Plugins/Runtime/AudioSynesthesia/Content
Paths=../../../Engine/Plugins/Experimental/ControlRig/Content
Paths=../../../Engine/Plugins/Media/MediaCompositing/Content
Paths=../../../Engine/Plugins/Runtime/Synthesis/Content
Paths=../../../Engine/Plugins/SequenceDialogue/Content
Paths=../../../Client/Plugins/Puerts/ReactUMG/Content
Paths=../../../Client/Plugins/genesis-ue-plugin/RenderExporter/Content
Paths=../../../Engine/Plugins/KuroiOSDelegate/Content
Paths=../../../Client/Plugins/KuroTDM/Content
Paths=../../../Client/Plugins/Kuro/KuroGachaTools/Content
Paths=../../../Client/Plugins/Kuro/KuroPushSdk/Content
Paths=../../../Client/Plugins/MagtModule/Content
Paths=../../../Client/Plugins/SpinePlugin/Content
Paths=../../../Client/Plugins/TpSafe/Content
Paths=../../../Engine/Plugins/AssetChecker/Content
Paths=../../../Engine/Plugins/Editor/SpeedTreeImporter/Content
Paths=../../../Engine/Plugins/Experimental/ChaosClothEditor/Content
Paths=../../../Engine/Plugins/Experimental/ChaosNiagara/Content
Paths=../../../Engine/Plugins/Experimental/ChaosSolverPlugin/Content
Paths=../../../Engine/Plugins/MagicLeap/MagicLeapPassableWorld/Content
Paths=../../../Engine/Plugins/MagicLeap/MagicLeap/Content
Paths=../../../Engine/Plugins/MegascansPlugin/Content
Paths=../../../Client/Plugins/Kuro/KuroCloudGame/Content
Paths=../../../Engine/Plugins/Developer/PixelDebug/Content
Paths=../../../Engine/Plugins/PWPlugin/Content
Paths=../../../Engine/Plugins/BlueprintFileUtils/Content
Paths=../../../Client/Plugins/Kuro/WeLingPipeSDK/Content
Paths=../../../Engine/Plugins/Runtime/Intel/XeSS/Content
Paths=../../../Engine/Plugins/Runtime/Nvidia/NRD/Content
Paths=../../../Client/Plugins/Kuro/KuroPSOTools/Content
Paths=../../../Client/Plugins/ComfyTextures/Content

[/Script/Engine.RendererSettings]
r.Color.Max=1.1 ;颜色最大值
r.Color.Mid=0.55 ;颜色中间值
r.KuroTonemapping=1 ;1 = 去除库洛滤镜（灰蒙蒙的）3 = 开启库洛滤镜
; 原版值: 1, 0.5, 3
; 图片对比: https://imgsli.com/MjczMTcz https://imgsli.com/MjczMTcw

r.ParticleLODBias=2147483647 ; 设置粒子系统的 LOD（层次细节）偏差：2147483647 = 粒子系统不使用 LOD
r.DetailMode=1 ; 场景细节
r.MaterialQualityLevel=2 ;材质
r.TemporalAA.MobileStaticFrameWeight=0.25 ; TAA静态帧权重
r.TemporalAA.MobileFrameWeight=0.25 ; TAA帧权重：影响平滑度
r.TemporalAA.MobileUpsampling=1 ; 是否启用TAA上采样
r.FidelityFX.FSR.SecondaryUpscale=1 ; 是否启用 FidelityFX 超分辨率（FSR）
r.FidelityFX.FSR.RCAS.Sharpness=1.0 ; FSR 锐化度
r.Upscale.Quality=3 ; 设置上采样质量
FX.BatchAsync=1 ; 启用异步批处理渲染
FX.EarlyScheduleAsync=1 ; 启用早期调度的异步渲染
r.AllowUseAnyLODAsOcclusionData=1 ; 剔除优化
r.AlsoUseSphereForFrustumCull=1 ; 剔除优化
tick.AllowAsyncTickCleanup=1 ; 启用异步清理 tick 计时器优化
tick.AllowAsyncTickDispatch=1 ; 启用异步的 tick 分发优化

[Core.Log]
global=none ; 禁用日志